// Keyword “arsenal” used to route users to the most helpful tool during panic
// Grouped into three buckets: breathing help, AI companion, and worship/music.

export const toBreatheKeywords: string[] = [
  'anxious','anxiety','panic','panic attack','overwhelmed','overwhelm','stressed','stress','pressure','tense','tension','tight chest','chest tightness','racing heart','fast heart','palpitations','short of breath','breathless','hyperventilate','hyperventilating','shaky','shaking','trembling','sweaty','sweating','fear','afraid','scared','worry','worried','worrying','jitters','jittery','restlessness','restless','unease','uneasy','on edge','doom','dread','meltdown','spiraling','spiral','triggered anxiety','urge to run','overload','sensory overload','freaking out','overthinking','mind racing','can\'t calm','cant calm','cannot calm','can\'t breathe','cant breathe','cannot breathe','can\'t focus','cant focus','cannot focus','grounding','ground me','need calm','calm me','calming','soothe','soothing','compose','compose myself','center myself','slow down','breathe','breath','breathing hard','breathing fast','inhale','exhale','count breaths','box breathing','guided breathing','breath prayer','jesus help me breathe','lightheaded','light headed','dizzy','dizziness','faint','faintness','numb','tingling','pins and needles','upset stomach','nausea','nauseous','shaky hands','tight jaw','clenched jaw','headache','migraine','tunnel vision','sweaty palms','hot flashes','chills','startle','startled','adrenaline','fight or flight','freeze','fawn','cortisol','burnout','burned out','fatigue','tired','exhausted','drained','insomnia','can\'t sleep','cant sleep','insomnia night','racing thoughts','mental fog','brain fog','overwhelmed at work','overwhelmed at school','social anxiety','meeting anxiety','performance anxiety','test anxiety','travel anxiety','airplane anxiety','crowds','claustrophobic','claustrophobia','agoraphobia','fear of panic','fear of failure','fear of people','fear of judgment','perfectionism','pressure to be perfect','time pressure','deadlines','tense shoulders','shallow breathing','deep breathing','diaphragmatic','relax','relaxation','rest','peace','be still','be still and know','psalm 46:10','god\'s peace','jesus calm my heart','holy spirit comfort','abba help','whisper of peace','gentle breath','slow breath','inhale grace','exhale fear','inhale peace','exhale stress','inhale jesus','exhale anxiety','hold breath','release breath','counted breathing','four seven eight','4-7-8','3-3-6','5-5-5','triangle breathing','square breathing','paced breathing','guided calm','grounding exercise','five senses','body scan','muscle relax','progressive relax','unclench','shoulders down','unclench jaw','soften gaze','safe place','i am safe','it will pass','anchor','anchor breath','present moment','here and now','gentle','steady','quiet my mind','calm my body','calm my soul','peace of christ','shalom'
];

export const toAIKeywords: string[] = [
  'tempted','temptation','urge','urges','trigger','triggered','relapse','slip','fall','falling','porn','porn site','nsfw','explicit','nude','nudity','sexual','sex','sexualized','lust','lustful','craving','crave','fantasy','fantasizing','images','videos','clip','clips','scrolling','doomscroll','late night','alone at night','isolated','isolation','privacy','incognito','incognito mode','private mode','secret tab','browsing','search','searching','keywords','aroused','arousal','turned on','horny','morning wood','edging','edging loop','peek','peeked','peeking','peek at','cam','webcam','camgirl','cam boy','live stream','live chat','dm','dms','sext','sexting','chat','chat now','dirty talk','hookup','tinder','bumble','hinge','instagram','reels','tiktok','shorts','twitter','x.com','reddit','subreddit','of','onlyfans','patreon adult','paywall','subscription','free trial','vpn','proxy','unblock','blocker','disable blocker','bypass','clear history','erase history','hide','hide screen','fake work','minimize','window switch','private browser','safari','chrome','firefox','brave','android browser','iphone browser','app store search','suggestive','clickbait','thumbnail','explore page','for you page','fyp','trending','suggestive ads','popups','spam','spammy','explicit link','fantasy spiral','shame spiral','guilt spiral','almost relapsed','almost did it','one more look','just a peek','just a little','compromise','boundary','boundaries','accountability','need plan','plan my escape','call a partner','text a partner','block me','lock me out','move phone','put phone away','leave the room','go outside','take a shower','cold shower','go to bed','tired trigger','boredom trigger','stress trigger','loneliness trigger','rejection trigger','curiosity trigger','fantasy trigger','routine trigger','payday trigger','travel trigger','hotel trigger','work trip','school break','finals week','after church','after work','weekend','sunday night','friday night','saturday night','payday','cash app','gift card','burner email','burner account','alt account','follow models','thirst trap','explore models','save images','stash','hidden folder','hidden album','lock notes','calculator app','delete apps','reinstall','new account','temptation rising','urge building','self control low','need help now','talk me down','coach me','ai coach','emergency coach','pray with me','bible verse','escape route','flee temptation','joseph ran','make a plan','call out','confess','honest talk','safe accountability'
];

export const toWorshipKeywords: string[] = [
  'sad','sadness','down','downcast','blue','low','heavy','heaviness','hopeless','despair','depressed','depression','weary','tired','exhausted','fatigue','drained','burdened','burden','shame','guilt','condemnation','regret','failure','broken','brokenhearted','heartbroken','lonely','alone','isolation','abandoned','rejected','emptiness','empty','numb','numbness','darkness','dark','fog','confusion','discouraged','discouragement','sorrow','grief','grieving','loss','mourning','cry','crying','tears','teary','ache','aching','pain','heartache','heaviness of soul','dry','dryness','desert','wilderness','silence','silent','distant','god feels distant','where are you god','why god','why me','why now','no joy','lost joy','lost hope','little faith','weak faith','strengthen me','encourage me','lift my head','lift me up','restore me','renew me','renew','restore','revive','revival in me','breathe again','breathe on me','comfort me','comfort','peace','shalom','presence','presence of god','presence of jesus','holy spirit','fill me','fill my heart','heal me','healing','healer','shepherd','psalm 23','psalm 34','psalm 42','psalm 91','isaiah 40','isaiah 41','matthew 11:28','come to me','give me rest','rest for my soul','quiet me','still me','be still','worship','praise','song','songs','music','hymn','hymns','sing','singing','playlist','soaking','soaking worship','gospel','adoration','thanksgiving','gratitude','thankful','bless the lord','bless the lord','hallelujah','alleluia','amen','maranatha','glory','glory to god','worthy','worthy is the lamb','holy','holy holy holy','faithful','faithfulness','goodness of god','mercy','grace','amazing grace','blessed assurance','it is well','great is thy faithfulness','way maker','promise keeper','light in darkness','cornerstone','living hope','oceans','build my life','worthy of it all','nothing else','here again','abide','abide with me','come holy spirit','fresh wind','new wine','secret place','altar','fire','oil','anointing','prayer','pray','praying','intercede','intercession','scripture','bible','verse','meditate','meditation','meditating','devotion','devotional','quiet time','morning prayer','night prayer','gratitude list','testimony','testimonies','encourage','encouragement','hope','hope in jesus','joy in jesus','peace of christ','love of god','draw near','come close','worship session'
];

export type PanicBuckets = {
  toBreathe: string[];
  toAI: string[];
  toWorship: string[];
};

export const panicBuckets: PanicBuckets = {
  toBreathe: toBreatheKeywords,
  toAI: toAIKeywords,
  toWorship: toWorshipKeywords,
};

export function matchBucket(text: string): 'breathe' | 'ai' | 'worship' | null {
  const t = (text || '').toLowerCase();
  const has = (arr: string[]) => arr.some((k) => t.includes(k));
  if (has(toBreatheKeywords)) return 'breathe';
  if (has(toAIKeywords)) return 'ai';
  if (has(toWorshipKeywords)) return 'worship';
  return null;
}
