default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
  # Prepare CI (keychain, derived data, etc.)
  setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: ENV["APPSTORE_PRIVATE_KEY_BASE64"] == "true",
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"],
      git_branch: ENV["MATCH_GIT_BRANCH"] || "main",
      git_token: ENV["MATCH_GIT_TOKEN"],
      app_identifier: [ENV["IOS_BUNDLE_ID"]],
      username: ENV["FASTLANE_USER"],
      team_id: ENV["IOS_TEAM_ID"],
      api_key: api_key
    )

  increment_build_number(xcodeproj: "PureHeart.xcodeproj")

    build_app(
      scheme: "PureHeart",
      workspace: "PureHeart.xcworkspace",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      include_bitcode: false,
      include_symbols: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end
