default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :testflight_deploy do
    # Automatic code signing with match
    match(
      type: "appstore",
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )
    
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "./pureheart.xcodeproj"
    )
    
    # Build the app
    build_app(
      workspace: "./pureheart.xcworkspace",
      scheme: "pureheart",
      export_method: "app-store",
      configuration: "Release"
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: ENV["FASTLANE_USER"],
      team_id: ENV["IOS_TEAM_ID"],
      ipa: "./pureheart.ipa"
    )
  end
end
