name: iOS TestFlight

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'web/**'
      - 'android/**'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    name: Build and Upload to TestFlight
    runs-on: macos-14
    timeout-minutes: 60
    env:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      RUBY_VERSION: ${{ secrets.RUBY_VERSION }}
      # App Store Connect
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
      IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      # CocoaPods speeds
      CP_HOME_DIR: /tmp/.cocoapods
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false

      - name: Install JS deps
        run: |
          npm ci --legacy-peer-deps --no-audit --no-fund

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ${{ env.CP_HOME_DIR }}
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install CocoaPods
        working-directory: ios
        run: |
          gem install cocoapods --no-document
          pod install --repo-update

      - name: Install Fastlane
        run: |
          gem install fastlane --no-document

      - name: Decode App Store Connect Key if base64
        shell: bash
        run: |
          KEY_PATH="$RUNNER_TEMP/AuthKey.p8"
          if echo "$APPSTORE_PRIVATE_KEY" | grep -q "BEGIN PRIVATE KEY"; then
            printf "%s" "$APPSTORE_PRIVATE_KEY" > "$KEY_PATH"
          else
            echo "Assuming base64 key";
            echo "$APPSTORE_PRIVATE_KEY" | base64 --decode > "$KEY_PATH"
          fi
          # Normalize line endings and ensure final newline
          awk '{ print } END { if (NR>0 && substr($0,length($0))!="\n") print "" }' "$KEY_PATH" > "$KEY_PATH.norm" && mv "$KEY_PATH.norm" "$KEY_PATH"
          echo "APPSTORE_KEY_FILE=$KEY_PATH" >> $GITHUB_ENV

      - name: Build and upload to TestFlight
        working-directory: ios
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
        run: |
          fastlane beta

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-archives
          path: |
            ios/build/**/*.ipa
            ~/Library/Developer/Xcode/Archives/**/*.xcarchive
            ~/Library/Logs/gym/*.log
            ~/Library/Logs/fastlane/*.log
