name: iOS TestFlight Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ secrets.RUBY_VERSION }}
          bundler-cache: true
          
      - name: Setup Keychain
        run: |
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD=temporary_password
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          echo "KEYCHAIN_PATH=$KEYCHAIN_PATH" >> $GITHUB_ENV
          echo "KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> $GITHUB_ENV
          
      - name: Setup Xcode
        run: |
          # GitHub Actions has Xcode in different locations
          # List available Xcode versions
          ls /Applications/ | grep Xcode
          # Use the latest stable Xcode (GitHub Actions default)
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          # Print Xcode version for debugging
          xcodebuild -version
          # Verify Xcode path
          xcode-select -p
          # Check if xcodebuild is accessible
          which xcodebuild
          
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          cd ios && pod install --repo-update
          
      - name: Fix iOS Deployment Target
        run: |
          cd ios
          # Update pods to use iOS 12.0 minimum
          pod install
          
      - name: Setup Fastlane
        run: |
          cd ios
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "fastlane"' >> Gemfile
          echo 'gem "cocoapods"' >> Gemfile
          echo 'gem "abbrev"' >> Gemfile
          echo 'gem "ostruct"' >> Gemfile
          bundle install
          
          # Create Appfile with API key authentication
          echo 'app_identifier("${{ secrets.IOS_BUNDLE_ID }}")' > fastlane/Appfile
          echo 'team_id("${{ secrets.IOS_TEAM_ID }}")' >> fastlane/Appfile
          
          # Create Matchfile
          # Use token-based authentication by embedding token in git URL
          GIT_URL_WITH_TOKEN=$(echo "${{ secrets.MATCH_GIT_URL }}" | sed "s|https://github.com/|https://x-access-token:${{ secrets.MATCH_GIT_TOKEN }}@github.com/|")
          echo "git_url(\"$GIT_URL_WITH_TOKEN\")" > fastlane/Matchfile
          echo 'storage_mode("git")' >> fastlane/Matchfile
          echo 'type("appstore")' >> fastlane/Matchfile
          echo 'app_identifier(["${{ secrets.IOS_BUNDLE_ID }}"])' >> fastlane/Matchfile
          
          # Create Fastfile for API key authentication
          cat > fastlane/Fastfile << 'EOL'
          default_platform(:ios)

          platform :ios do
            desc "Deploy to TestFlight"
            lane :testflight_deploy do
              # Setup API Key authentication
              api_key = app_store_connect_api_key(
                key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
                issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
                key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
                is_key_content_base64: true,
                duration: 1200
              )
              
              # Automatic code signing with match
              match(
                type: "appstore",
                readonly: true,
                api_key: api_key
              )
              
              # Build the app
              gym(
                workspace: "PureHeart.xcworkspace",
                scheme: "PureHeart",
                export_method: "app-store",
                configuration: "Release",
                clean: true,
                output_name: "PureHeart.ipa",
                xcargs: "-allowProvisioningUpdates IPHONEOS_DEPLOYMENT_TARGET=12.0",
                verbose: true,
                disable_xcpretty: true,
                buildlog_path: "./logs",
                skip_profile_detection: true
              )
              
              # Upload to TestFlight
              upload_to_testflight(
                api_key: api_key,
                skip_waiting_for_build_processing: true,
                skip_submission: true,
                distribute_external: false
              )
            end
          end
          EOL
          
      - name: Create React Native Bundle
        run: |
          # Clean any existing build artifacts
          rm -rf ios/build
          rm -rf ios/DerivedData
          # Create the bundle directory if it doesn't exist
          mkdir -p ios/PureHeart
          # Generate React Native bundle for iOS release
          npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/PureHeart/main.jsbundle --assets-dest ios/PureHeart
          
      - name: Clean Xcode Cache
        run: |
          cd ios
          # Clean build folder (DerivedData is in different location on GitHub Actions)
          rm -rf build/
          # Clean workspace
          xcodebuild clean -workspace PureHeart.xcworkspace -scheme PureHeart
          
      - name: Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
          KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
          KEYCHAIN_PASSWORD: ${{ env.KEYCHAIN_PASSWORD }}
          # React Native specific environment variables
          NODE_BINARY: node
          SKIP_BUNDLING: 1
          RCT_NO_LAUNCH_PACKAGER: 1
          # Suppress React Native warnings
          XCODE_WARN_UNUSED_VARIABLES: NO
        run: |
          cd ios
          bundle exec fastlane testflight_deploy
