name: iOS TestFlight Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ secrets.RUBY_VERSION }}
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          npm ci
          cd ios && pod install
          
      - name: Setup Fastlane
        run: |
          cd ios
          bundle add fastlane
          bundle install
          
      - name: Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
        run: |
          cd ios
          bundle exec fastlane testflight_deploy
